# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BenchmarkTools]]
deps = ["JSON", "Logging", "Printf", "Statistics", "UUIDs"]
git-tree-sha1 = "9e62e66db34540a0c919d72172cc2f642ac71260"
uuid = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
version = "0.5.0"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[Bzip2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "3663bfffede2ef41358b6fc2e1d8a6d50b3c3904"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.6+2"

[[Cairo]]
deps = ["Cairo_jll", "Colors", "Fontconfig_jll", "Glib_jll", "Graphics", "Libdl", "Pango_jll"]
git-tree-sha1 = "f9db9e9814f71799e1b9c849055f0adae8bdc158"
uuid = "159f3aea-2a34-519c-b102-8c37f9878175"
version = "1.0.3"

[[Cairo_jll]]
deps = ["Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "d296f5e975306844de3e57118c3cf4a7cf2a8762"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.0+4"

[[CodeTracking]]
deps = ["InteractiveUtils", "UUIDs"]
git-tree-sha1 = "cab4da992adc0a64f63fa30d2db2fd8bec40cab4"
uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
version = "0.5.11"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "c73d9cfc2a9d8433dc77f5bff4bddf46b1d78c20"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.10.3"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Reexport"]
git-tree-sha1 = "2fdeb981ebcf52cd800ddb6a0aa5eac34153552d"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "ed2c4abadf84c53d9e58510b5fc48912c2336fbb"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "2.2.0"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "7d7578b00789cf16c5f68fad71868e773edd58a2"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.17.16"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Expat_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9cdd4b1523086c9d93604599e3a389e8941e52b0"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.7+1"

[[FileIO]]
deps = ["Pkg"]
git-tree-sha1 = "202335fd24c2776493e198d6c66a6d910400a895"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.3.0"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[FixedPointNumbers]]
git-tree-sha1 = "3ba9ea634d4c8b289d590403b4a06f8e227a6238"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.0"

[[Fontconfig_jll]]
deps = ["Bzip2_jll", "Expat_jll", "FreeType2_jll", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "141fe5f6d4013304d2ca5af0ac20ef4855bcc4e5"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.1+11"

[[FreeType2_jll]]
deps = ["Bzip2_jll", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "7d900f32a3788d4eacac2bfa3bf5c770179c8afd"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.1+2"

[[FriBidi_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "2f56bee16bd0151de7b6a1eeea2ced190a2ad8d4"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.5+3"

[[Gettext_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "e43d686df1f45cab7a2570ff63642a3ea618ca5f"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.20.1+2"

[[Glib_jll]]
deps = ["Gettext_jll", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "09ea3797c586eedbb383eb8f1c950a12923f1541"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.59.0+2"

[[Gloria]]
deps = ["BenchmarkTools", "Cairo", "Colors", "Compat", "DataStructures", "FileIO", "IterTools", "Libdl", "LinearAlgebra", "Revise", "Rsvg", "SimpleDirectMediaLayer", "SnoopCompile", "StaticArrays"]
pr on own repo
uuid = "5b2e8964-9f3b-11e8-3f79-610468876dfe"
version = "0.1.0"

[[Graphics]]
deps = ["Colors", "LinearAlgebra", "NaNMath"]
git-tree-sha1 = "45d684ead5b65c043ad46bd5be750d61c39d7ef8"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "1.0.2"

[[Graphite2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "6fad1258f2c9eacb86e8726d38c2ad6549f9d91e"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.13+1"

[[HarfBuzz_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Gettext_jll", "Glib_jll", "Graphite2_jll", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "7a206ed46082e986179586a4ed60cbc740313ea6"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.6.1+5"

[[Homebrew]]
deps = ["BinDeps", "InteractiveUtils", "JSON", "Libdl", "Test", "Unicode"]
git-tree-sha1 = "f01fb2f34675f9839d55ba7238bab63ebd2e531e"
uuid = "d9be37ee-ecc9-5288-90f1-b9ca67657a75"
version = "0.7.1"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IterTools]]
git-tree-sha1 = "05110a2ab1fc5f932622ffea2a003221f4782c18"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.3.0"

[[JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "b34d7cef7b337321e97d22242c3c2b91f476748e"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.0"

[[JpegTurbo_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b007cedc10bb017cdae3af0062fe4dd29b483c70"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.0.1+0"

[[JuliaInterpreter]]
deps = ["CodeTracking", "InteractiveUtils", "Random", "UUIDs"]
git-tree-sha1 = "12289ab2f9ff307a603a42b20ed83e20717cc475"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.7.15"

[[LZO_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "71119990371c93f027bee80547ee908ddfe7c5ca"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.0+1"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libcroco_jll]]
deps = ["Glib_jll", "Libdl", "Pkg", "XML2_jll"]
git-tree-sha1 = "07425268e18745928d11cd280e7fcd607d9b6082"
uuid = "57eb2189-7eb1-52c8-ac0e-99495f550b14"
version = "0.6.13+1"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libffi_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "68b165c609961207baa3174e03d6d56e7a37124c"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.1+1"

[[Libgcrypt_jll]]
deps = ["Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "7efb7f5e75a0f7323cce366d3e44a2d225c5617a"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.5+1"

[[Libgpg_error_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "334284a62d6b8592099d28b78c76aefc266c03a2"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.36.0+1"

[[Libiconv_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "e5256a3b0ebc710dbd6da0c0b212164a3681037f"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.0+2"

[[Libmount_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "621a6d7d527fd8e4812ca1154567bfdb81a3c517"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.34.0+1"

[[Librsvg_jll]]
deps = ["Libcroco_jll", "Libdl", "Pango_jll", "Pkg", "gdk_pixbuf_jll"]
git-tree-sha1 = "04b0edcdfbbca4b4cef65ff92a3a8ed11697bae7"
uuid = "925c91fb-5dd6-59dd-8e8c-345e74382d89"
version = "2.42.2+1"

[[Libtiff_jll]]
deps = ["JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "1fe8c3608dfe7bdec81d018de1cc66e959016e8c"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.1.0+0"

[[Libuuid_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7ae7eee3a9fe811b656347700c17fc9620ef4ecf"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.34.0+4"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[LoweredCodeUtils]]
deps = ["JuliaInterpreter"]
git-tree-sha1 = "695206e7ec13cbec6e6ee4d19af7464e80f4d1ad"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
version = "0.4.4"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NaNMath]]
git-tree-sha1 = "928b8ca9b2791081dc71a51c55347c27c618760f"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.3"

[[OrderedCollections]]
git-tree-sha1 = "12ce190210d278e12644bcadf5b21cbdcf225cd3"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.2.0"

[[PCRE_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "2c860a32ae9c421b52b654448bd31a31f437449a"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.42.0+2"

[[Pango_jll]]
deps = ["Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "HarfBuzz_jll", "Libdl", "Pkg"]
git-tree-sha1 = "cd19789f20bde5d45e96a7e937db9a6a024412e6"
uuid = "36c8627f-9965-5494-a995-c6b170f724f3"
version = "1.42.4+8"

[[Parsers]]
deps = ["Dates", "Test"]
git-tree-sha1 = "f0abb338b4d00306500056a3fd44c221b8473ef2"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "1.0.4"

[[Pixman_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "ae66367153a89ecb2a5c7acc2df4ba082b729b6a"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.38.4+2"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Test", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Revise]]
deps = ["CodeTracking", "Distributed", "FileWatching", "JuliaInterpreter", "LibGit2", "LoweredCodeUtils", "OrderedCollections", "Pkg", "REPL", "UUIDs", "Unicode"]
git-tree-sha1 = "3185d2ee31756af9e20ce045ddfaedcd0df9e4aa"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "2.6.6"

[[Rsvg]]
deps = ["Cairo", "Glib_jll", "Librsvg_jll"]
git-tree-sha1 = "3d3dc66eb46568fb3a5259034bfc752a0eb0c686"
uuid = "c4c386cf-5103-5370-be45-f3a111cca3b8"
version = "1.0.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[SimpleDirectMediaLayer]]
deps = ["BinDeps", "ColorTypes", "Compat", "Homebrew", "Libdl", "Test"]
git-tree-sha1 = "3e8076dbbb43ed4448356604f5f8ec0a15ac2eaf"
uuid = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
version = "0.1.1"

[[SnoopCompile]]
deps = ["OrderedCollections", "Pkg", "Serialization"]
git-tree-sha1 = "ba4d5e2fbf54ca0068149301442df93abcfbb4c0"
uuid = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
version = "1.2.3"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "5c06c0aeb81bef54aed4b3f446847905eb6cbda0"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.12.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[URIParser]]
deps = ["Unicode"]
git-tree-sha1 = "53a9f49546b8d2dd2e688d216421d050c9a31d0d"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.1"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[XML2_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "987c02a43fa10a491a5f0f7c46a6d3559ed6a8e2"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.9+4"

[[XSLT_jll]]
deps = ["Libdl", "Libgcrypt_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "c287bbc08773474ab1d12849eb46b961a325e149"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.33+2"

[[Xorg_libX11_jll]]
deps = ["Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "bbfb646a5a86dc636041c8ee945799b69d37fdba"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+2"

[[Xorg_libXau_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "711f2bbdbb0e90b90a71c5ccf835137e2def539a"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+2"

[[Xorg_libXdmcp_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "1ffd7bc9c9d8bba6652516f3402ee1ef5f4cac70"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+2"

[[Xorg_libXext_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "079acccb5437761d93c483f2edb5fc3ed21ea7db"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+2"

[[Xorg_libXrender_jll]]
deps = ["Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "d5492a36d33359cf93ad573ea5e235cd71728649"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+2"

[[Xorg_libpthread_stubs_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "ec1e2973e4e624069be95f806dbd7e225fee26c6"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+1"

[[Xorg_libxcb_jll]]
deps = ["Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "c1efb50fb6a8c40c45451611fbf93feabe5f9611"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+2"

[[Xorg_xtrans_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "b6e7d70f5fc9e3fde505539194c8caaab3c40ebf"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+1"

[[Zlib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "2f6c3e15e20e036ee0a0965879b31442b7ec50fa"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+9"

[[Zstd_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "f23995a6ab76d634865204fe0a4e7254d1a6d1f9"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.4.4+1"

[[gdk_pixbuf_jll]]
deps = ["Glib_jll", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg", "Xorg_libX11_jll", "libpng_jll"]
git-tree-sha1 = "566ebf4b2c9efd81b35eb914c325026831077f39"
uuid = "da03df04-f53b-5353-a52f-6a8b0620ced0"
version = "2.38.2+6"

[[libpng_jll]]
deps = ["Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "594cb058723c13941cf463fd09e5859499594f50"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.37+3"
